### ISSUE TITLE
Forget password/Reset Password

### ISSUE THREAD

**Issue by mayur-home** [mayur-home/smart-interviewer#6]
If user forgets password then he should able to reset the password.
- Should send email to registered user email id with OTP.
- User enters that OTP in screen.
- If that matches then Reset Password screen should be displayed and consumer can change his password.

**Comment by hardikkaji** [comment]
[](url)

**Comment by hardikkaji** [comment]
Only ChangePassword API Integration is pending. Rest part is merged in Dev.

**Comment by hardikkaji** [comment]
[https://github.com/mayur-home/smart-interviewer/pull/19](url)

Closing this issue. PR Created.
